apiVersion: v1

kind: Service

metadata:
  name: application-service
  labels:
    name: application-service
    app: demo-app
    
spec:
  type: LoadBalancer
  ports:
   - port: 8087
     targetPort: 8087
  selector:
    name: application-pod
    app: demo-app